modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/rotisami19/Pet-Compass/issues"

[[mods]]
modId="petcompass"
version="${file.jarVersion}"
displayName="Pet Compass"
logoFile="logo.png"
authors="rotisami19"
description='''
A simple compass to find your lost pets.
'''

[[dependencies.petcompass]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.petcompass]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"
